### ISSUE TITLE
Dangerous use of unescaped variable expansion

### ISSUE THREAD

**Issue by bergsas** [aheimsbakk/idid#1]
Hi there,

You are living dangerously here:

$ grep -nE '(=\$|[^"]\$@)' idid 
96:    local query_second=$(date -d "$*" +%s)
98:        local file_date=$(echo $f | egrep -o '[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}') 
99:        local file_second=$(date -d $file_date +%s)
119:        local logs=$(find "$STR" -type f -name \*log -printf "%P\n")
241:NOW_DATE=$(date -u +%F)
242:NOW_TIME=$(date -u +%T)
243:STR=${IDID_STORE:-"$HOME/.idid"}
244:GIT=${IDID_STORE_GIT:-"$STR/.git"}
254:    ls|list|show)           shift;  cmd_ls $@;;
255:    log)                    shift;  cmd_log $@;;
256:    add)                    shift;  cmd_add $@;;
257:    tags)                   shift;  cmd_tags $@;;
258:    last)                   shift;  cmd_last $@;;
259:    git)                    shift;  cmd_git $@;;

Line 99/119 may also break on filenames with special characters (spaces, tabs, vertical tabs, new lines).

See: https://www.gnu.org/software/bash/manual/bashref.html#index-_0024_0040

-Erlend

**Comment by aheimsbakk** [comment]
Thank you for pointing it out. I've gone through the script and fixed missing quotes.

Please check out the latest version 0.11.

Greetings 
-Arnulf
